package share.book.domain.book;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import share.book.domain.account.UserAccountEntity;
import share.book.domain.rental.RentalEntity;
import share.book.infra.jpa.BaseEntity;

/**
 * ProductEntity generated by hbm2java
 */
@Entity
@Table(name="product"
)
public class ProductEntity extends BaseEntity implements java.io.Serializable {


     private String id;
     private BookEntity book;
     private UserAccountEntity userAccount;
     private String description;
     private String returnDate;
     private int rentalPeriod;
     private Set<RentalEntity> rentals = new HashSet<RentalEntity>(0);
     private Set<ReviewEntity> reviews = new HashSet<ReviewEntity>(0);

    public ProductEntity() {
    }

	
    public ProductEntity(String id, BookEntity book, UserAccountEntity userAccount, String description, int rentalPeriod) {
        this.id = id;
        this.book = book;
        this.userAccount = userAccount;
        this.description = description;
        this.rentalPeriod = rentalPeriod;
    }
    public ProductEntity(String id, BookEntity book, UserAccountEntity userAccount, String description, String returnDate, int rentalPeriod, Set<RentalEntity> rentals, Set<ReviewEntity> reviews) {
       this.id = id;
       this.book = book;
       this.userAccount = userAccount;
       this.description = description;
       this.returnDate = returnDate;
       this.rentalPeriod = rentalPeriod;
       this.rentals = rentals;
       this.reviews = reviews;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=22)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="book_id", nullable=false)
    public BookEntity getBook() {
        return this.book;
    }
    
    public void setBook(BookEntity book) {
        this.book = book;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_account_id", nullable=false)
    public UserAccountEntity getUserAccount() {
        return this.userAccount;
    }
    
    public void setUserAccount(UserAccountEntity userAccount) {
        this.userAccount = userAccount;
    }

    
    @Column(name="description", nullable=false, length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="return_date", length=10)
    public String getReturnDate() {
        return this.returnDate;
    }
    
    public void setReturnDate(String returnDate) {
        this.returnDate = returnDate;
    }

    
    @Column(name="rental_period", nullable=false)
    public int getRentalPeriod() {
        return this.rentalPeriod;
    }
    
    public void setRentalPeriod(int rentalPeriod) {
        this.rentalPeriod = rentalPeriod;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="product")
    public Set<RentalEntity> getRentals() {
        return this.rentals;
    }
    
    public void setRentals(Set<RentalEntity> rentals) {
        this.rentals = rentals;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="product")
    public Set<ReviewEntity> getReviews() {
        return this.reviews;
    }
    
    public void setReviews(Set<ReviewEntity> reviews) {
        this.reviews = reviews;
    }




}


