package share.book.domain.book;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import share.book.domain.rental.RentalEntity;
import share.book.infra.jpa.BaseEntity;

/**
 * ReviewEntity generated by hbm2java
 */
@Entity
@Table(name="review"
)
public class ReviewEntity extends BaseEntity implements java.io.Serializable {


     private String id;
     private ProductEntity product;
     private RentalEntity rental;
     private int evaluation;
     private String comment;

    public ReviewEntity() {
    }

    public ReviewEntity(String id, ProductEntity product, RentalEntity rental, int evaluation, String comment) {
       this.id = id;
       this.product = product;
       this.rental = rental;
       this.evaluation = evaluation;
       this.comment = comment;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=22)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false)
    public ProductEntity getProduct() {
        return this.product;
    }
    
    public void setProduct(ProductEntity product) {
        this.product = product;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="rental_id", nullable=false)
    public RentalEntity getRental() {
        return this.rental;
    }
    
    public void setRental(RentalEntity rental) {
        this.rental = rental;
    }

    
    @Column(name="evaluation", nullable=false)
    public int getEvaluation() {
        return this.evaluation;
    }
    
    public void setEvaluation(int evaluation) {
        this.evaluation = evaluation;
    }

    
    @Column(name="comment", nullable=false, length=100)
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


