package share.book.domain.rental;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import share.book.domain.account.UserAccountEntity;
import share.book.domain.book.ProductEntity;
import share.book.domain.book.ReviewEntity;
import share.book.infra.jpa.BaseEntity;

/**
 * RentalEntity generated by hbm2java
 */
@Entity
@Table(name="rental"
)
public class RentalEntity extends BaseEntity implements java.io.Serializable {


     private String id;
     private ProductEntity product;
     private UserAccountEntity userAccount;
     private String rentalDate;
     private String rentalStates;
     private Set<ReviewEntity> reviews = new HashSet<ReviewEntity>(0);

    public RentalEntity() {
    }

	
    public RentalEntity(String id, ProductEntity product, UserAccountEntity userAccount, String rentalStates) {
        this.id = id;
        this.product = product;
        this.userAccount = userAccount;
        this.rentalStates = rentalStates;
    }
    public RentalEntity(String id, ProductEntity product, UserAccountEntity userAccount, String rentalDate, String rentalStates, Set<ReviewEntity> reviews) {
       this.id = id;
       this.product = product;
       this.userAccount = userAccount;
       this.rentalDate = rentalDate;
       this.rentalStates = rentalStates;
       this.reviews = reviews;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=22)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false)
    public ProductEntity getProduct() {
        return this.product;
    }
    
    public void setProduct(ProductEntity product) {
        this.product = product;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_account_id", nullable=false)
    public UserAccountEntity getUserAccount() {
        return this.userAccount;
    }
    
    public void setUserAccount(UserAccountEntity userAccount) {
        this.userAccount = userAccount;
    }

    
    @Column(name="rental_date", length=10)
    public String getRentalDate() {
        return this.rentalDate;
    }
    
    public void setRentalDate(String rentalDate) {
        this.rentalDate = rentalDate;
    }

    
    @Column(name="rental_states", nullable=false, length=100)
    public String getRentalStates() {
        return this.rentalStates;
    }
    
    public void setRentalStates(String rentalStates) {
        this.rentalStates = rentalStates;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rental")
    public Set<ReviewEntity> getReviews() {
        return this.reviews;
    }
    
    public void setReviews(Set<ReviewEntity> reviews) {
        this.reviews = reviews;
    }




}


