package share.book.domain.account;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import share.book.domain.book.ProductEntity;
import share.book.domain.rental.RentalEntity;
import share.book.infra.jpa.BaseEntity;

/**
 * UserAccountEntity generated by hbm2java
 */
@Entity
@Table(name="user_account"
)
public class UserAccountEntity extends BaseEntity implements java.io.Serializable {


     private String id;
     private String email;
     private String phoneNumber;
     private Set<ProductEntity> products = new HashSet<ProductEntity>(0);
     private UserDetailEntity userDetail;
     private Set<RentalEntity> rentals = new HashSet<RentalEntity>(0);

    public UserAccountEntity() {
    }

	
    public UserAccountEntity(String id, String email, String phoneNumber) {
        this.id = id;
        this.email = email;
        this.phoneNumber = phoneNumber;
    }
    public UserAccountEntity(String id, String email, String phoneNumber, Set<ProductEntity> products, UserDetailEntity userDetail, Set<RentalEntity> rentals) {
       this.id = id;
       this.email = email;
       this.phoneNumber = phoneNumber;
       this.products = products;
       this.userDetail = userDetail;
       this.rentals = rentals;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=22)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="email", nullable=false, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="phone_number", nullable=false, length=100)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userAccount")
    public Set<ProductEntity> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<ProductEntity> products) {
        this.products = products;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="userAccount")
    public UserDetailEntity getUserDetail() {
        return this.userDetail;
    }
    
    public void setUserDetail(UserDetailEntity userDetail) {
        this.userDetail = userDetail;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userAccount")
    public Set<RentalEntity> getRentals() {
        return this.rentals;
    }
    
    public void setRentals(Set<RentalEntity> rentals) {
        this.rentals = rentals;
    }




}


