package share.book.domain.account;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import share.book.infra.jpa.BaseEntity;

/**
 * UserDetailEntity generated by hbm2java
 */
@Entity
@Table(name="user_detail"
)
public class UserDetailEntity extends BaseEntity implements java.io.Serializable {


     private String userAccountId;
     private UserAccountEntity userAccount;
     private String firstName;
     private String lastName;
     private String nickName;
     private String birthDay;
     private String profile;
     private String address;

    public UserDetailEntity() {
    }

	
    public UserDetailEntity(UserAccountEntity userAccount, String firstName, String lastName, String nickName, String profile, String address) {
        this.userAccount = userAccount;
        this.firstName = firstName;
        this.lastName = lastName;
        this.nickName = nickName;
        this.profile = profile;
        this.address = address;
    }
    public UserDetailEntity(UserAccountEntity userAccount, String firstName, String lastName, String nickName, String birthDay, String profile, String address) {
       this.userAccount = userAccount;
       this.firstName = firstName;
       this.lastName = lastName;
       this.nickName = nickName;
       this.birthDay = birthDay;
       this.profile = profile;
       this.address = address;
    }
   
     @GenericGenerator(name="share.book.domain.account.UserDetailEntityIdGenerator", strategy="foreign", parameters=@Parameter(name="property", value="userAccount"))@Id @GeneratedValue(generator="share.book.domain.account.UserDetailEntityIdGenerator")

    
    @Column(name="user_account_id", unique=true, nullable=false, length=22)
    public String getUserAccountId() {
        return this.userAccountId;
    }
    
    public void setUserAccountId(String userAccountId) {
        this.userAccountId = userAccountId;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public UserAccountEntity getUserAccount() {
        return this.userAccount;
    }
    
    public void setUserAccount(UserAccountEntity userAccount) {
        this.userAccount = userAccount;
    }

    
    @Column(name="first_name", nullable=false, length=100)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", nullable=false, length=100)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="nick_name", nullable=false, length=100)
    public String getNickName() {
        return this.nickName;
    }
    
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    
    @Column(name="birth_day", length=10)
    public String getBirthDay() {
        return this.birthDay;
    }
    
    public void setBirthDay(String birthDay) {
        this.birthDay = birthDay;
    }

    
    @Column(name="profile", nullable=false, length=1000)
    public String getProfile() {
        return this.profile;
    }
    
    public void setProfile(String profile) {
        this.profile = profile;
    }

    
    @Column(name="address", nullable=false, length=100)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }




}


